Description: Metastore Template , 09/06/2020 - FSS

# Stack Name: Nombre-Apellido-Datalab-Metastore-Stack

Parameters:
  Proyecto:
    Description: proyecto indeed
    Default: tfm
    Type: String
    
  Entorno:
    Description: Seleccione el entorno
    Default: dev
    Type: String
    AllowedValues:
    - dev
    - int
    - pre
    - prod
  Estudiante:
    Description:  grupo3-indeed
    Type: String


Resources:
  WebdataGlueDatabase:
    Type: AWS::Glue::Database
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseInput: 
        Name: !Sub ${Estudiante}-${Proyecto}-webdata-${Entorno}
        Description: Base de datos indeed
        LocationUri:
          Fn::Join:
          - ''
          - - 's3://'
            - Fn::ImportValue: !Sub ${Estudiante}-${Proyecto}-landing-bucket-id-${Entorno}
            - '/webdata'
            
  WebScrapingGlueCrawler: 
    Type: AWS::Glue::Crawler
    Properties: 
      Name: !Sub ${Estudiante}-${Proyecto}-webdata-${Entorno}
      Role: !ImportValue 
        Fn::Sub:  ${Estudiante}-${Proyecto}-glue-service-role-id-${Entorno}
      DatabaseName: !Ref WebdataGlueDatabase
      SchemaChangePolicy: 
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DELETE_FROM_DATABASE
      Targets: 
        S3Targets:
        - Path:
            Fn::Join:
            - ''
            - - 's3://'
              - Fn::ImportValue: !Sub ${Estudiante}-${Proyecto}-landing-bucket-id-${Entorno}
              - '/webdata/webscraping'

Outputs:

  WebdataGlueDatabaseId:
    Description: ID del recurso (= nombre, en este caso).
    Value: !Ref WebdataGlueDatabase
    Export:
      Name: !Sub ${Estudiante}-${Proyecto}-webdata-database-id-${Entorno}

  WebScrapingGlueCrawlerId:
    Description: ID del recurso (= nombre, en este caso).
    Value: !Ref WebScrapingGlueCrawler
    Export:
      Name: !Sub ${Estudiante}-${Proyecto}-webscraping-crawler-id-${Entorno}